### ISSUE TITLE
More of a tip

### ISSUE THREAD

**Issue by computermouth** [fordsfords/axp209-nolim#1]
> This startup script was cloned from /etc/init.d/udev-finish
> I learned about the SysV init scripts at https://wiki.debian.org/LSBInitScripts
> I still don't understand run levels in Debian. :-(

So Debian's migrated to this thing called Systemd as opposed to SysV init. It's a hotbed of debate, but the primary interest is that systemd should be faster, permitting threaded startup. While there currently exists these SysV init compatibilites, one day, they'll likely all be gone.

Runlevels and startup scripts are replaced with Targets and .service files respectively [sort of]. Systemd's big targets of note: 
- multi-user.target -> tty login
- graphical.target -> xorg launch

Anyways, I personally learn better by example:
https://github.com/NextThingCo/chip-input-reset/blob/chip/stable/chip-input-reset/system/chip-local.service
https://github.com/NextThingCo/pocketchip-load/blob/master/pocketchip-load/system/pocketchip-load.service

For documentation and specifics, I usually go to the ArchWiki:
https://wiki.archlinux.org/index.php/systemd

But feel free to stick with what works!

**Comment by fordsfords** [comment]
Thanks!  I set up "blink" as a service, and had no idea which one was considered the "wave of the future".  I'll definitely do some more learning on it.

And especially thanks for responding to my lament about not understanding run levels!
